### ISSUE TITLE
你好！阅读了您的论文后非常受到启发，在运行您的代码时创建环境这一步时报错解决不了，请问可以指导一下如何解决吗

### ISSUE THREAD

**Issue by TangHaooooo** [songwenas12/fjsp-drl#2]

**Comment by TangHaooooo** [comment]
Traceback (most recent call last):
  File ".\fjsp-drl-main\fjsp-drl-main\test.py", line 203, in <module>
    main()
  File ".\fjsp-drl-main\fjsp-drl-main\test.py", line 140, in main
    env = gym.make('fjsp-v0', case=[test_file], env_paras=env_test_paras, data_source='file')
  File "D:\anaconda3\envs\d2l\lib\site-packages\gym\envs\registration.py", line 601, in make
    env = PassiveEnvChecker(env)
  File "D:\anaconda3\envs\d2l\lib\site-packages\gym\wrappers\env_checker.py", line 22, in __init__
    assert hasattr(
AssertionError: You must specify a action space. https://www.gymlibrary.ml/content/environment_creation/

**Comment by Goh-IE** [comment]
In my case, when I downgraded the version of gym to 0.18.0 this problem has been resolved!

**Comment by TangHaooooo** [comment]
Thanks very much for your reply!
